-- MySQL Script generated by MySQL Workbench
-- Пт 04 сен 2020 21:41:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`registr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`registr` ;

CREATE TABLE IF NOT EXISTS `test`.`registr` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Familiya` VARCHAR(255) NULL,
  `Login` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`tovar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`tovar` ;

CREATE TABLE IF NOT EXISTS `test`.`tovar` (
  `tovar_id` INT NOT NULL AUTO_INCREMENT,
  `Foto_t` VARCHAR(45) NULL,
  `Name_t` VARCHAR(45) NULL DEFAULT '',
  `cena_t` INT NULL,
  `type` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  PRIMARY KEY (`tovar_id`),
  UNIQUE INDEX `tovar_id_UNIQUE` (`tovar_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `test`.`zakaz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test`.`zakaz` ;

CREATE TABLE IF NOT EXISTS `test`.`zakaz` (
  `id_zakaz` INT NOT NULL AUTO_INCREMENT,
  `registr_id` INT NOT NULL,
  `tovar_tovar_id` INT NOT NULL,
  `cena_z` INT NOT NULL,
  `count_tovar` INT NOT NULL,
  PRIMARY KEY (`id_zakaz`, `registr_id`, `tovar_tovar_id`),
  INDEX `fk_orders_has_tovar_tovar1_idx` (`tovar_tovar_id` ASC),
  UNIQUE INDEX `id_zakaz_UNIQUE` (`id_zakaz` ASC),
  INDEX `fk_zakaz_registr1_idx` (`registr_id` ASC),
  CONSTRAINT `fk_orders_has_tovar_tovar1`
    FOREIGN KEY (`tovar_tovar_id`)
    REFERENCES `test`.`tovar` (`tovar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zakaz_registr1`
    FOREIGN KEY (`registr_id`)
    REFERENCES `test`.`registr` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `test`.`registr`
-- -----------------------------------------------------
START TRANSACTION;
USE `test`;
INSERT INTO `test`.`registr` (`id`, `Name`, `Familiya`, `Login`, `Password`) VALUES (1, 'Пашок', 'Грунин', 'admin', 'admin');
INSERT INTO `test`.`registr` (`id`, `Name`, `Familiya`, `Login`, `Password`) VALUES (2, 'Елена', 'Корнякова', 'mama', 'mama');
INSERT INTO `test`.`registr` (`id`, `Name`, `Familiya`, `Login`, `Password`) VALUES (3, 'Евген', 'Евгенич', 'baron', 'baron');
INSERT INTO `test`.`registr` (`id`, `Name`, `Familiya`, `Login`, `Password`) VALUES (4, 'Димас', 'Королев', 'gammu', 'gammu');
INSERT INTO `test`.`registr` (`id`, `Name`, `Familiya`, `Login`, `Password`) VALUES (5, 'Серёга', 'Рычагов', 'chemodan', 'chemodan');
INSERT INTO `test`.`registr` (`id`, `Name`, `Familiya`, `Login`, `Password`) VALUES (6, 'Ирина', 'Смирнова', 'tet', 'tet');

COMMIT;


-- -----------------------------------------------------
-- Data for table `test`.`tovar`
-- -----------------------------------------------------
START TRANSACTION;
USE `test`;
INSERT INTO `test`.`tovar` (`tovar_id`, `Foto_t`, `Name_t`, `cena_t`, `type`, `color`) VALUES (1, '1o.jpg', 'Футбольный мяч', 300, 'шар', 'белый');
INSERT INTO `test`.`tovar` (`tovar_id`, `Foto_t`, `Name_t`, `cena_t`, `type`, `color`) VALUES (3, '2o.jpg', 'Шар с супер героиней ', 250, 'шар', 'красный');
INSERT INTO `test`.`tovar` (`tovar_id`, `Foto_t`, `Name_t`, `cena_t`, `type`, `color`) VALUES (5, '10.jpeg', 'С днём рождения', 350, 'шар', 'жёлтый');
INSERT INTO `test`.`tovar` (`tovar_id`, `Foto_t`, `Name_t`, `cena_t`, `type`, `color`) VALUES (6, '11.jpg', 'С днём рождения', 335, 'шар', 'синий');
INSERT INTO `test`.`tovar` (`tovar_id`, `Foto_t`, `Name_t`, `cena_t`, `type`, `color`) VALUES (8, '12.jpg', 'С днём рождения', 345, 'шар', 'цветной');
INSERT INTO `test`.`tovar` (`tovar_id`, `Foto_t`, `Name_t`, `cena_t`, `type`, `color`) VALUES (10, '13.jpg', 'Сердечко С днём рождения', 360, 'шар', 'золотистый');

COMMIT;

